#!/bin/bash

# opens a file or URL in the user's preferred application, see man xdg-open
alias ']'='xdg-open'

# list directories first
alias 'lsd'='ls --color -h --group-directories-first'

# git
gcom() {
  git commit -m $1
}

# short / no untracked files
alias gsts='git status -s -uno'

gcou() {
  git checkout $1
}

gac() {
  git add $1
  git commit
}

# convert any-ffmpeg-format to mp3
ffmpeg-mp3() {

  ffmpeg -i $1
}

# public ip
pubip() {
    curl ipinfo.io/ip
}

pdf2png() {
    # cut filename
    STR=$1
    PNGPATH=${STR:0:-4}
    echo "Generating $PNGPATH.png"
    convert $1 -density 300 $PNGPATH
}

# list all user installed packages
#ls-apt-pkg() {
#    comm -23 <(apt-mark showmanual | sort -u) <(gzip -dc /var/log/installer/initial-status.gz | sed -n 's/^Package: //p' | sort -u)
#}

py3-configure() {
    ./configure --enable-loadable-sqlite-extensions --enable-optimizations
}

save_power() {
    sudo /home/chris/.rc/linux/save_power.sh
}

smallify() {
    convert -resize 50% -quality 80 "$1" "$2"
}

backup() {
    cd ~/.bak;
    sh bak_extern.sh /media/chris/3B25-7776
}

youtube-dl-best() {
    youtube-dl -f bestvideo+bestaudio "$1"
}
#pdf resize
pdf-minify() {
    gs -sDEVICE=pdfwrite -dCompatibilityLevel=1.4 -dPDFSETTINGS=/ebook -dNOPAUSE -dQUIET -dBATCH -sOutputFile=$2 $1
}

pdf-minify-2() {

gs  -q  -dNOPAUSE -dBATCH -dSAFER \
	-sDEVICE=pdfwrite \
	-dCompatibilityLevel=1.3 \
	-dPDFSETTINGS=/screen \
	-dEmbedAllFonts=true \
	-dSubsetFonts=true \
	-dColorImageDownsampleType=/Bicubic \
	-dColorImageResolution=72 \
	-dGrayImageDownsampleType=/Bicubic \
	-dGrayImageResolution=72 \
	-dMonoImageDownsampleType=/Bicubic \
	-dMonoImageResolution=72 \
	-sOutputFile=out.pdf \
	 $1
}

pdf-minify-3() {
    convert -compress Zip -density 150x150 $1 $2
}
alias "new_lease"="sudo dhclient -r; sudo dhclient;"

duration() {
    ffmpeg -i $1 2>&1 | grep Duration | awk '{print $2}' | tr -d ,
    }

alias "c=xclip"
alias "v=xclip -o"

append() {
  cat >> "${1}" <(echo "${2}")
}

# Downloads music via youtube-dl and converts with ffmpeg to mp3
ytdl() {
youtube-dl -f bestaudio --extract-audio --audio-format mp3 --audio-quality 0 --embed-thumbnail "${1}"
}
